CREATE DATABASE `scraping_data` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `link_compare` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `url` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `url_UNIQUE` (`url`)
) ENGINE=InnoDB AUTO_INCREMENT=13501 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `funda` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Prijs` int NOT NULL,
  `Status` text,
  `Wonen` int NOT NULL,
  `Adres` text,
  `Postcode` int DEFAULT NULL,
  `Stad` text,
  `Url` varchar(500) CHARACTER SET big5 COLLATE big5_chinese_ci DEFAULT NULL,
  `Sold` text,
  `Verkoopdatum` text,
  `Looptijd` text,
  `Aangebodensinds` text,
  `Aanvaarding` text,
  `Soortwoonhuis` text,
  `Soortbouw` text,
  `Bouwjaar` text,
  `Soortdak` text,
  `Overigeinpandigeruimte` text,
  `Gebouwgebondenbuitenruimte` text,
  `Perceel` text,
  `Inhoud` text,
  `Aantalkamers` int DEFAULT NULL,
  `Aantalbadkamers` int DEFAULT NULL,
  `Badkamervoorzieningen` text,
  `Aantalwoonlagen` text,
  `Voorzieningen` text,
  `Energielabel` text,
  `Isolatie` text,
  `Verwarming` text,
  `Warmwater` text,
  `Cvketel` text,
  `Oppervlakte` text,
  `Eigendomssituatie` text,
  `Ligging` text,
  `Tuin` text,
  `Soortgarage` text,
  `Capaciteit` text,
  `Soortparkeergelegenheid` text,
  `Aanbieder` text,
  `Aanbiederbereikbaar` text,
  `Aanbiedertelefoonnummer` text,
  `Achtertuin` text,
  `Balkondakterras` text,
  `Slaapkamers` int DEFAULT NULL,
  `Toiletten` int DEFAULT NULL,
  `Onderbod` text,
  `VerkochtOnderVoorbehoud` text,
  `x` double DEFAULT NULL,
  `y` double DEFAULT NULL,
  `PostcodeLetters` text,
  `scraped_date` text,
  `VVE` varchar(60000) DEFAULT NULL,
  `Servicekosten` text,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Url_UNIQUE` (`Url`)
) ENGINE=InnoDB AUTO_INCREMENT=717905 DEFAULT CHARSET=latin1;
